__author__ = "Keenan Noack"
__email__ = "AlbertUnruh@pm.me"
__url__ = "https://github.com/AlbertUnruh/AlbertUnruhUtils.py"
__license__ = "MIT"
__copyright__ = f"(c) 2021 - present {__author__}"
__version__ = "3.0.0"
__description__ = "A collection of utils written in Python."
